### ISSUE TITLE
Request for Spark! Tech Resources for NAACP

### ISSUE THREAD

**Issue by dagon8** [BU-Spark/se-naacp-spring22#3]
- Daniel Gonzalez dagon@bu.edu
 - Acces to a paid version of firebase
 - We are moving the csv files belonging to NAACP from the SCC to the firebase database. The paid version will help avoid space issues when transferring those files.

**Comment by IanSaucy** [comment]
Do you already have a project on firebase?

**Comment by dagon8** [comment]
Not yet. I have been using a personal firebase account to understand how to manipulate the csv files, but nothing official.

**Comment by dagon8** [comment]
Not yet. I have been using a personal firebase account to understand how to manipulate the csv files, but nothing official.

**Comment by IanSaucy** [comment]
Sorry for the slow response. Can you ping me during the week of August 1 for this? I'm on vacation next week.

**Comment by IanSaucy** [comment]
Created here: https://console.firebase.google.com/project/se-naacp-journalism-bias/overview
